services:
  web:
    build: .
    image: unizq
    environment:
      - JDBC_DB_USERNAME=${JDBC_DB_USERNAME}
      - JDBC_DB_NAME=${JDBC_DB_NAME}
      - JDBC_DB_PORT=${JDBC_DB_PORT}
      - JDBC_DB_PASSWORD=${JDBC_DB_PASSWORD}
      - JDBC_DB_HOST=${JDBC_DB_HOST}
      - BASE_URL=${BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
