services:
  web:
    build:
      context: .
      args:
        - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
        - VERTEXAI_REFRESH_TOKEN=${VERTEXAI_REFRESH_TOKEN}
        - VERTEXAI_CLIENT_ID=${VERTEXAI_CLIENT_ID}
        - VERTEXAI_CLIENT_SECRET=${VERTEXAI_CLIENT_SECRET}
        - VERTEXAI_PROJECT_ID=${VERTEXAI_PROJECT_ID}
    image: unizq

    environment:
      - JDBC_DB_USERNAME=${JDBC_DB_USERNAME}
      - JDBC_DB_NAME=${JDBC_DB_NAME}
      - JDBC_DB_PORT=${JDBC_DB_PORT}
      - JDBC_DB_PASSWORD=${JDBC_DB_PASSWORD}
      - JDBC_DB_HOST=${JDBC_DB_HOST}
      - BASE_URL=${BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
      - VERTEXAI_PROJECT_ID=${VERTEXAI_PROJECT_ID}
      - VERTEXAI_MODEL=${VERTEXAI_MODEL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - VERTEXAI_REFRESH_TOKEN=${VERTEXAI_REFRESH_TOKEN}
      - VERTEXAI_CLIENT_ID=${VERTEXAI_CLIENT_ID}
      - VERTEXAI_CLIENT_SECRET=${VERTEXAI_CLIENT_SECRET}

    ports:
      - "8080:8080"
