[build]
builder = "nixpacks"
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 9735c45 (fix toml file)
buildCommand = "bash build_script.bash.sh"

[deploy]
startCommand = "export JAVA_HOME=backend/java && export PATH=$JAVA_HOME/bin:$PATH && cd backend && chmod +x ./gradlew && ./gradlew clean build && ./gradlew bootRun"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
<<<<<<< HEAD
=======
>>>>>>> 2f50da0 (add config to railway.toml)
buildCommand = "echo building!"
=======
buildCommand = "bash build_script.bash.sh"
>>>>>>> 8fea4ab (add config to railway.toml)

[deploy]
startCommand = "chmod +x ./gradlew && ./gradlew clean build && ./gradlew bootRun
"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
=======
>>>>>>> 9735c45 (fix toml file)
