[build]
builder = "nixpacks"
buildCommand = "bash build_script.bash.sh"

[deploy]
startCommand = "chmod +x ./gradlew && ./gradlew clean build && ./gradlew bootRun"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
